-- ============================================================================
-- Java E-Commerce System - PostgreSQL schema
--
-- Chạy file này khi đang kết nối đúng database "ecommerce".
-- Script sẽ XÓA và TẠO LẠI toàn bộ 6 bảng persistence hiện có của project.
-- Không chạy trên database đang chứa dữ liệu cần giữ lại.
-- ============================================================================

BEGIN;

SET search_path TO public;

-- Xóa bảng con trước bảng cha để có thể chạy lại script nhiều lần.
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS carts CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Xóa enum cũ sau khi các bảng phụ thuộc đã được xóa.
DROP TYPE IF EXISTS order_status_enum;
DROP TYPE IF EXISTS cart_status_enum;
DROP TYPE IF EXISTS product_type_enum;
DROP TYPE IF EXISTS product_status_enum;
DROP TYPE IF EXISTS user_status_enum;
DROP TYPE IF EXISTS user_role_enum;

-- Giá trị enum phải trùng chính xác với các enum Java vì repository sử dụng
-- Enum.name() khi ghi và Enum.valueOf() khi đọc dữ liệu.
CREATE TYPE user_role_enum AS ENUM (
    'ADMIN',
    'NORMAL_USER'
);

CREATE TYPE user_status_enum AS ENUM (
    'ACTIVE',
    'PENDING',
    'BANNED'
);

CREATE TYPE product_status_enum AS ENUM (
    'ACTIVE',
    'INACTIVE',
    'ARCHIVED'
);

CREATE TYPE product_type_enum AS ENUM (
    'PHYSICAL',
    'DIGITAL'
);

CREATE TYPE cart_status_enum AS ENUM (
    'ACTIVE',
    'CHECKED_OUT'
);

-- Java hiện đặt tên trạng thái thành SUCESSFUL (một chữ C), vì vậy database
-- giữ đúng tên này để JdbcOrderRepository có thể chuyển đổi bằng valueOf().
CREATE TYPE order_status_enum AS ENUM (
    'PENDING_PAYMENT',
    'SUCCESSFUL',
    'CANCELLED',
    'FAILED'
);

-- ==========================================================================
-- USERS
-- ==========================================================================
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(255) NOT NULL,
    phone_number    VARCHAR(50),
    email           VARCHAR(320) NOT NULL,
    role            user_role_enum NOT NULL DEFAULT 'NORMAL_USER',
    status          user_status_enum NOT NULL DEFAULT 'PENDING',
    password_hash   VARCHAR(255) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_phone_number UNIQUE (phone_number),
    CONSTRAINT ck_users_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_users_email_not_blank CHECK (btrim(email) <> ''),
    CONSTRAINT ck_users_password_hash_not_blank CHECK (btrim(password_hash) <> ''),
    CONSTRAINT ck_users_phone_not_blank CHECK (
        phone_number IS NULL OR btrim(phone_number) <> ''
    )
);

-- Không cho phép hai email chỉ khác chữ hoa/chữ thường.
CREATE UNIQUE INDEX uq_users_email_case_insensitive
    ON users (lower(email));

-- ==========================================================================
-- PRODUCTS
-- ==========================================================================
CREATE TABLE products (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(255) NOT NULL,
    quantity        INTEGER NOT NULL DEFAULT 0,
    price           NUMERIC(19, 2) NOT NULL,
    status          product_status_enum NOT NULL DEFAULT 'ACTIVE',
    type            product_type_enum NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    weight          NUMERIC(10, 3),

    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT uq_products_name UNIQUE (name),
    CONSTRAINT ck_products_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_products_quantity_non_negative CHECK (quantity >= 0),
    CONSTRAINT ck_products_price_positive CHECK (price > 0),
    CONSTRAINT ck_products_weight_matches_type CHECK (
        (type = 'PHYSICAL' AND weight IS NOT NULL AND weight > 0)
        OR
        (type = 'DIGITAL' AND weight IS NULL)
    )
);

CREATE INDEX idx_products_status_type
    ON products (status, type);

-- ==========================================================================
-- CARTS
-- Một user có thể có nhiều giỏ hàng trong lịch sử.
-- ==========================================================================
CREATE TABLE carts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id         BIGINT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status          cart_status_enum NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT pk_carts PRIMARY KEY (id),
    CONSTRAINT fk_carts_user FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,

    -- Phục vụ khóa ngoại kép của orders, bảo đảm order thuộc đúng user/cart.
    CONSTRAINT uq_carts_user_id_and_id UNIQUE (user_id, id)
);

CREATE INDEX idx_carts_user_created_at
    ON carts (user_id, created_at DESC);

-- ==========================================================================
-- CART ITEMS
-- Một sản phẩm chỉ xuất hiện một lần trong cùng một giỏ hàng.
-- ==========================================================================
CREATE TABLE cart_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cart_id         BIGINT NOT NULL,
    product_id      BIGINT NOT NULL,
    quantity        INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT pk_cart_items PRIMARY KEY (id),
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id)
        REFERENCES carts (id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id)
        REFERENCES products (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT uq_cart_items_cart_product UNIQUE (cart_id, product_id),
    CONSTRAINT ck_cart_items_quantity_positive CHECK (quantity > 0)
);

CREATE INDEX idx_cart_items_product_id
    ON cart_items (product_id);

-- ==========================================================================
-- ORDERS
-- Mỗi cart chỉ được checkout thành một order. Khóa ngoại kép ngăn trường hợp
-- tạo order bằng user_id không phải chủ sở hữu của cart_id.
-- ==========================================================================
CREATE TABLE orders (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id             BIGINT NOT NULL,
    cart_id             BIGINT NOT NULL,
    status              order_status_enum NOT NULL DEFAULT 'PENDING_PAYMENT',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sub_total           NUMERIC(19, 2) NOT NULL,
    shipping_fee        NUMERIC(19, 2) NOT NULL DEFAULT 0,
    discount_amount     NUMERIC(19, 2) NOT NULL DEFAULT 0,
    total_price         NUMERIC(19, 2) NOT NULL,

    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT fk_orders_user_cart FOREIGN KEY (user_id, cart_id)
        REFERENCES carts (user_id, id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT uq_orders_cart UNIQUE (cart_id),
    CONSTRAINT ck_orders_sub_total_positive CHECK (sub_total > 0),
    CONSTRAINT ck_orders_shipping_fee_non_negative CHECK (shipping_fee >= 0),
    CONSTRAINT ck_orders_discount_non_negative CHECK (discount_amount >= 0),
    CONSTRAINT ck_orders_discount_not_too_large CHECK (
        discount_amount <= sub_total + shipping_fee
    ),
    CONSTRAINT ck_orders_total_price_non_negative CHECK (total_price >= 0),
    CONSTRAINT ck_orders_total_price_correct CHECK (
        total_price = sub_total + shipping_fee - discount_amount
    )
);

CREATE INDEX idx_orders_user_created_at
    ON orders (user_id, created_at DESC);

CREATE INDEX idx_orders_status_created_at
    ON orders (status, created_at DESC);

-- ==========================================================================
-- ORDER ITEMS
-- unit_price là snapshot giá tại thời điểm checkout, không tự thay đổi khi
-- giá trong products được cập nhật sau này.
-- ==========================================================================
CREATE TABLE order_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id        BIGINT NOT NULL,
    product_id      BIGINT NOT NULL,
    quantity        INTEGER NOT NULL,
    unit_price      NUMERIC(19, 2) NOT NULL,

    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id)
        REFERENCES orders (id)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id)
        REFERENCES products (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT uq_order_items_order_product UNIQUE (order_id, product_id),
    CONSTRAINT ck_order_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_order_items_unit_price_positive CHECK (unit_price > 0)
);

CREATE INDEX idx_order_items_product_id
    ON order_items (product_id);

-- Mô tả ngắn để xem trực tiếp trong Database tool của IntelliJ/PostgreSQL.
COMMENT ON TABLE users IS 'Tài khoản người dùng của hệ thống';
COMMENT ON TABLE products IS 'Sản phẩm vật lý và sản phẩm số';
COMMENT ON TABLE carts IS 'Giỏ hàng hiện tại và lịch sử giỏ hàng của người dùng';
COMMENT ON TABLE cart_items IS 'Các sản phẩm và số lượng trong giỏ hàng';
COMMENT ON TABLE orders IS 'Thông tin tổng tiền và trạng thái của đơn hàng';
COMMENT ON TABLE order_items IS 'Snapshot sản phẩm, số lượng và đơn giá khi checkout';

COMMIT;

-- Truy vấn kiểm tra sau khi chạy script.
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_type = 'BASE TABLE'
ORDER BY table_name;
